name: auto-tag

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  tag:
    name: 🔖 Tag Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: go-semantic-release/action@v1
        with:
          changelog-file: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
